clone:
  git:
    image: plugins/git
    depth: 50
    recursive: true

pipeline:
  test:
    image: dealroom/php:1.0-${PHP_VERSION}
    group: backend
    commands:
      - php -v
      - composer -V
      - cp .env.ci .env
      - composer install --prefer-dist -q -n
      - ./vendor/bin/codecept run unit -vvv

services:
  database:
    image: mysql:5.7
    volumes:
      - /home/rush/Projects/tests/drone/mysql-tests:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret123
      - MYSQL_DATABASE=dealroom_testing
      - MYSQL_USER=dealroom
      - MYSQL_PASSWORD=secret

  elasticsearch:
    image: dealroom/elasticsearch

  memcached:
    image: memcached:1.5

  gearman:
    image: moltar/gearmand:latest


matrix:
  PHP_VERSION:
    - 7.1
    - 7.2

branches: [master, dev, pr/*]
